### PR TITLE
Use captureException for Sentry

### PR DESCRIPTION
**Pull request by lex111**

### CODE REVIEW

**Comment by ovr** [comment]
@lex111 

image

**Comment by lex111** [comment]
@ovr um, what do I need to do? 
I thought that there should not be such errors, just need a comment `// eslint-disable-next-line no-undef`

**Comment by ovr** [comment]
@lex111 Вверху строчку удалить))

image

**Comment by lex111** [comment]
@ovr oops, done :white_check_mark:

**Comment by ovr** [comment]
Thank you @lex111 

image

**Pull request merged**
