### PR TITLE
Add npm scripts to quick develop

### PR DESCRIPTION
**Pull request by lex111**
Run packager + build app with a simple command 'npm run start:android' or  'npm run start:ios' instead of starting them in two terminals.

**Important note:**

The opening of the UI debugger was also added, although it is convenient for me personally, but other members may not need this, but I do not know how to check flags (arguments) in npm scripts, maybe there is a way to do something like this:

```sh
$ npm run start:android --debugger # open debugger after execute commands
```

It would be desirable to make within the limits of these two scripts, instead of to add still additional two, like so:

```diff
- start:ios: "concurrently -r 'react-native start' 'npm run ios && google-chrome http://localhost:8081/debugger-ui'",
- start:android: "concurrently -r 'react-native start' 'npm run android && google-chrome http://localhost:8081/debugger-ui'",

+ start:ios: "concurrently -r 'react-native start' 'npm run ios ",
+ start:android: "concurrently -r 'react-native start' 'npm run android",
+ start:ios:debug": concurrently -r 'react-native start' 'npm run ios && google-chrome http://localhost:8081/debugger-ui'",
+ start:android:debug": concurrently -r 'react-native start' 'npm run android && google-chrome http://localhost:8081/debugger-ui'",
```

That's why I did not do it, because there is a way to pass flags and check them (with the help of a ternary operator)?

### CODE REVIEW

**Comment by ovr** [comment]
Don't use `react-native start`, because this can be a big problem, I am using skip cache to protect problems

**Comment by lex111** [comment]
@ovr you mean, need to add `--reset-cache`? And what about opening a link with a debugger, what are the choices?

**Comment by ovr** [comment]
@lex111 yes, about > ` start --reset-cache`

**Comment by lex111** [comment]
@ovr ok, but what can I do with the opening of the debugger link?

**Comment by ovr** [comment]
> but what can I do with the opening of the debugger link?

are you sure that it's rly needed? As I known it opens auto for me

**Comment by lex111** [comment]
This is convenient, but I did not open it with `npm run start:android`, for example, but at the same time I wanted to still have this possibility, for example, so` npm run start: android --debugger`, but can this be done? That's the question, or introduce two more commands that open the debugger, e.g. `npm run start:android:debug`

**Comment by ovr** [comment]
Thank you 👍

**Pull request merged**
